apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: mongodb-triggered-job
  namespace: keda-sample
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: mng-dotnet-worker
          image: venkateshsrini3/mng-dotnet-worker:1.0
          env:
            - name: MongoDB__connectionString
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secrets
                  key: connectionString
        restartPolicy: Never
  pollingInterval: 30   # How often KEDA will poll MongoDB (in seconds)
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 20
  maxReplicaCount: 10   # Maximum number of jobs to run in parallel
  triggers:
  - type: mongodb
    metadata:
      # Required
      authenticationRef: 
        name: mongodb-trigger 
      dbName: candies
      collection: Candies-ToProcess
      query: '{ProcessingStatus:{$exists:true, $eq:"created"}}'  # Adjust your query accordingly
      queryValue: "1"  # The threshold above which KEDA will start scaling jobs
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mongodb-trigger 
spec:
  secretTargetRef:
    - parameter: connectionString
      name: mongodb-secret
      key: connect

