apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: mongodb-triggered-job
  namespace: keda-sample
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: mng-dotnet-worker
          image: venkateshsrini3/mng-dotnet-worker:1.12
          env:
          - name: MongoDB__connectionString
            valueFrom:
              secretKeyRef:
                name: mongo-db-secrets
                key: connectionString
          - name: podName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        restartPolicy: Never
  pollingInterval: 60   # How often KEDA will poll MongoDB (in seconds)
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 20
  maxReplicaCount: 10   # Maximum number of jobs to run in parallel
  triggers:
  - type: mongodb
    metadata:
      dbName: candies
      collection: Candies-ToProcess
      query: "{\"ProcessingStatus\":{\"$exists\":true, \"$eq\":\"created\"}}"  # Adjust your query accordingly
      queryValue: "1"  # The threshold above which KEDA will start scaling jobs
    authenticationRef: 
      name: mongodb-trigger 
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mongodb-trigger 
  namespace: keda-sample
spec:
  secretTargetRef:
  - parameter: connectionString
    name: mongo-db-secrets
    key: connectionString

